#!/bin/bash


show() {
	cat $BOOKMARKS_PATH | less
}


edit() {
	$EDITOR $BOOKMARKS_PATH
}


help() {
    echo Args: s, e, help
}


if [ $# -eq 0 ]; then
    show
elif [ $# -eq 1 ]; then
    if [ $1 == "s" ]; then
        show
    elif [ $1 == "e" ]; then
		edit
	elif [ $1 == "help" ]; then
        help
	else
	    echo Unknown argument, use \"help\"
    fi
else
    help
fi
