#!/bin/python

import sys
import openai

openai.api_key = 'API_KEY'

response = openai.ChatCompletion.create(
    model='gpt-3.5-turbo',
    messages=[
        {'role': 'user', 'content': sys.argv[1]},
    ]
)

print(response['choices'][0]['message']['content'])
