#!/bin/sh

dirs=`find $1 -maxdepth 1 -type d -exec realpath {} \;`

for dir in $dirs
do
    cd $dir
    res=`git status $dir 2> /dev/null | grep "not staged"`
    if [[ $? -eq 0 ]]; then
        pwd
    fi
done
